### ISSUE TITLE
Dev container creation fails

### ISSUE THREAD

**Issue by EliahKagan** [EliahKagan/NuHello#48]
Trying to spin up a dev container in a GitHub Codespaces gives:

```text
.devcontainer/postCreate: Customizing pwsh (PowerShell)...
Update-Help: Your current culture is (Invariant Language (Invariant Country)), which is not associated with any language, consider changing your system culture or install the English-US help content using: Update-Help -UICulture en-US.
[2882 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.

Error: Command failed: .devcontainer/postCreate
{"outcome":"error","message":"Command failed: .devcontainer/postCreate","description":"The postCreateCommand in the devcontainer.json failed.","containerId":"1ec738e572e9053d13beea15816f315146d3a8439e9c638f847af1ff10a8855f"}
    at WY (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bl (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:4393)
    at async Ll (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3738)
    at async vl (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2942)
    at async Js (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2386)
    at async QAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:1496)
    at async kK (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:964)
    at async NAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:3660)
    at async vC (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:4775)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: .devcontainer/postCreate
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.
```

**Comment by EliahKagan** [comment]
Fixed in #50
